version: "3.9"

services:
  postgres-db:
    container_name: postgres-bookaband
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookaband
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    hostname: "postgres-bookaband-local"
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    container_name: mongodb-bookaband
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: bookaband
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - default

  redis:
    container_name: redis-bookaband
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - default

#  backend:
#    container_name: bookaband-backend
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    ports:
#      - "4000:4000"
#    depends_on:
#      postgres-db:
#        condition: service_healthy
#      mongo:
#        condition: service_started
#      redis:
#        condition: service_started
#    networks:
#      - default
#    restart: unless-stopped

volumes:
  pgdata:

networks:
  default:
    name: bookaband-network
    external: true
