import * as dotenv from "dotenv";

dotenv.config();

const AUTHORIZE_SERVICE_PRIVATE_KEY = process.env.AUTHORIZE_SERVICE_PRIVATE_KEY;

const TOKEN_TYPE = "Bearer";

const ACCESS_TOKEN_EXPIRES_IN_SECONDS = Number(
  process.env.ACCESS_TOKEN_EXPIRES_IN_SECONDS,
);

const REFRESH_TOKEN_EXPIRES_IN_SECONDS = Number(
  process.env.REFRESH_TOKEN_EXPIRES_IN_SECONDS,
);

const TOKEN_ISSUER = "learning-platform-backend";

export {
  AUTHORIZE_SERVICE_PRIVATE_KEY,
  TOKEN_TYPE,
  ACCESS_TOKEN_EXPIRES_IN_SECONDS,
  REFRESH_TOKEN_EXPIRES_IN_SECONDS,
  TOKEN_ISSUER,
};
